### ISSUE TITLE
能否支持本地文件系统？

### ISSUE THREAD

**Issue by colin4k** [coderabbit214/bibliothecarius#26]
现在是必须使用oss来存储文件？上传文件就报错。。。application.yaml里面是设置阿里云存储，但是源码里面是amazon s3？

**Comment by caoshengdong** [comment]
默认需要使用 OSS，不过你可以使用 MINIO 来代替这个部分。

**Comment by coderabbit214** [comment]
@colin4k 常用的对象存储都支持s3协议
