### ISSUE TITLE
你好，诚心请教～

### ISSUE THREAD

**Issue by Remielpub** [coderabbit214/bibliothecarius#28]
你好，我对你开源的项目很有兴趣，在我花费了一周的时间，终于搭建好了环境，但是在开始测试时，出现一些问题。所以诚心想您请教。
1.我根据你发布的教程，进行测试时，和文档中显示的结果不同，original字段没有内容，请问这个是哪里的问题呢？
![20230417173020](https://user-images.githubusercontent.com/13202618/232445102-c04b8b52-1f51-40ba-b494-05ef5be7eac6.jpg)

2.我这边的目的是想训练一个业务客服的机器人，根据提供的业务文档，回复有关业务的问题。请问我想要实现目的，使用哪种模型更合适，同时如何训练模型呢？ （我是一名Android方向的开发者，对于AI 了解的不是很多，所以问题比较多，实在不好意思～～）

期待你的回复，灰常感谢～～

**Comment by coderabbit214** [comment]
可以留个邮箱 我发你微信我们沟通一下
@Remielpub R

**Comment by panyy** [comment]
@Remielpub 老哥，我也是Android开发，最近我们公司也要搞这个，有机会交流一下啊。

**Comment by Remielpub** [comment]
哈哈，原来都是道友～～ 要不加个QQ吧&nbsp; 咱们一起学习一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coderabbit214/bibliothecarius"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [coderabbit214/bibliothecarius] 你好，诚心请教～ (Issue #28)





 
@Remielpub 老哥，我也是Android开发，最近我们公司也要搞这个，有机会交流一下啊。
