### ISSUE TITLE
配置后运行问题

### ISSUE THREAD

**Issue by guoziting112** [coderabbit214/bibliothecarius#29]
配置完成后，按照步骤2.docker-compose启动后端服务,启动后终端显示：
![暂存](https://user-images.githubusercontent.com/118614101/233888412-d27e34df-5ebe-4637-9893-a3adf9c17af2.png)
之后按照步骤3.验证后端服务，点击网址，出现：
<img width="904" alt="image" src="https://user-images.githubusercontent.com/118614101/233888724-5ed20af4-cf76-4ed3-9401-db620ca0fb08.png">
我想问，是我文件配置出错了，还是配置文件是对的，已经启动后端服务了，但是因为代理问题

**Comment by guoziting112** [comment]
我现在应该是配置成功了
<img width="986" alt="image" src="https://user-images.githubusercontent.com/118614101/234202364-0f2355d9-c1d4-46b5-97c9-8b410dbc5072.png">
但是我在启动后端验证服务时还是出现上述情况，拒绝请求连接，
请问是什么原因呀～

**Comment by guoziting112** [comment]
您好，我携带了端口：8080
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/118614101/234238860-bb8df8d2-77ef-4ad1-9a9e-b5f4f78afdb7.png">

**Comment by caoshengdong** [comment]
你可以打印一下日志看看后端是不是没有正确启动，docker compose logs -f，或者直接用 docker compose up 启动

**Comment by guoziting112** [comment]
您好，我在docker dashboard中关闭了项目，然后尝试在终端中启动它，采用的命令是docker-compose up -d ，然后出现了架构问题：
<img width="566" alt="image" src="https://user-images.githubusercontent.com/118614101/234241868-bd56cd1a-754f-4ce5-b681-0d1f40552c0d.png">

**Comment by caoshengdong** [comment]
你用的是 ARM 的 Linux？

**Comment by guoziting112** [comment]
我使用的是 ARM 架构的M1芯片的 macOS 系统

**Comment by caoshengdong** [comment]
我和另一位开发都是在用 Apple Silicon 的 Macbook 开发，所以应该不存在问题。但是你这里报错提示说你的系统是 Linux，你在虚拟机中运行吗？

**Comment by guoziting112** [comment]
您好，我没有打开虚拟机，以上终端是macOS自带的terminal，我不熟悉docker的设置，但是我通过官网完成了下载，没有进行其他配置的修改，然后依次安装了mysql与qdrant（可以通过docker images查看到），所有都是默认设置，在执行 docker-compose up -d 时出现以上问题。我不知道是否应该更改哪些配置，也不了解docker的运行环境，您能给一些建议吗？或许我应该先学习使用docker？

**Comment by caoshengdong** [comment]
我们先确定一下，晚点给你答复。

**Comment by caoshengdong** [comment]
非常抱歉，经过我们检查之后，之前的 Dockerfile 引用的镜像确实有一些问题，我们已经在 PR #30 中修复了这个问题。如果你还有相关的问题，请你 reopen 这个 issue，我们很乐意为您解答。

**Comment by guoziting112** [comment]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/118614101/234439017-09da7e9d-f2cf-41ab-8f33-d35434143fb6.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/118614101/234438765-639a850f-4e7e-421e-afbe-992a630ebf44.png">
您好，我在PR#30中重新拉取code，然后按照步骤重新进行相关配置，还是出现第一章图所显示原因。同时我注意到关于bibliothecarius中的日志信息，说是启动了defult，这个意思是我自己的配置文件没有生效嘛，可能是这个原因嘛？

**Comment by caoshengdong** [comment]
因为更换了 Dockerfile 文件，所以你在启动的时候需要添加 `--force-recreate` 参数。[https://docs.docker.com/engine/reference/commandline/compose_up/#:~:text=If%20you%20want%20to%20force,the%20exit%20code%20is%200%20.](url)。第二张截图来看，你的配置文件确实没有生效。

**Comment by guoziting112** [comment]
我按照您给的命令重新启动之后：
又出现这样的问题
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/118614101/234444841-dc2c9c2c-7439-4eaa-b04f-4194824c6f92.png">
命令行还是显示：
<img width="613" alt="image" src="https://user-images.githubusercontent.com/118614101/234445070-4eea1278-a3be-4ef2-bef4-05179b4be738.png">

这个还是我配置原因嘛？

**Comment by guoziting112** [comment]
好的，您指的配置文件是：application.example.yaml嘛？那我这个datasource URL 指得就是mysql的url吧，我现在的配置文件application.example.yaml这样的：
<img width="883" alt="image" src="https://user-images.githubusercontent.com/118614101/234447026-d9917c0f-0f70-41d6-abf4-e4309000ab50.png">
同时docker-compose是这样的：
<img width="642" alt="image" src="https://user-images.githubusercontent.com/118614101/234447111-a886c769-a3e4-4a1a-bab1-d731de84e668.png">
我哪里需要修改嘛？

**Comment by caoshengdong** [comment]
如果你已经安装了 MySQL 和 qDrant 的话，那么你不需要考虑项目根目录下的 docker-compose.yml，因为这个 docker-compose.yml 是用来启动 MySQL 和 qDrant 的。你需要将 application.example.yaml 命名为 application.yaml 以应用配置。

**Comment by guoziting112** [comment]
现在我想利用您的docker-compose启动mysql 和 qdrant 两个容器，那么我该如何配置application.yaml下的mysql的url配置文件，使得bibliothecarius-1的container和 mysql容器进行连接呢？现在我已经成功启动了mysql 和 qdrant 两个容器，同时我尝试这样配置mysql的 url ，
<img width="821" alt="image" src="https://user-images.githubusercontent.com/118614101/234527666-efb4bf72-e624-4d88-b3c7-1893672bbaff.png">
将bibliothecarius-1的容器和mysql容器进行连接，但是还是出错，错误和上面一样：
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/118614101/234527765-3eb5cb3f-5c39-4065-900c-323f64adfdf3.png">
所以想问您这个url到底怎么配置才能生效呢？感谢

**Comment by caoshengdong** [comment]
最简单的办法是，直接使用 localhost 或者 127.0.0.1 以及对应的端口来配置你的数据库和 qdrant，因为在 docker-compose 中你已经暴露了相应的端口，可以在本地访问。

**Comment by guoziting112** [comment]
您好，我按照您的方式现在配置了，使用命令docker ps 检测启动的容器，也有对应的bibliothecarius 容器，<img width="602" alt="image" src="https://user-images.githubusercontent.com/118614101/234635153-dd4f55cd-8940-4c98-bb4d-a14451d08a1d.png">
但是我在启动后端验证服务时，出现
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/118614101/234635790-50581147-6927-45cc-af75-9556ec45d348.png">
请问这个会是什么原因呢？应该不是配置的问题了吧

**Comment by guoziting112** [comment]
您好，我又看了一下，是dockerfile中这行命令没执行吧～
<img width="969" alt="image" src="https://user-images.githubusercontent.com/118614101/234638589-3c9ec31c-dae5-4810-ae2b-343071e95109.png">

**Comment by guoziting112** [comment]
好的，辛苦您了～
我的email是：guozitingsweet@163.com
