### ISSUE TITLE
failed to solve: lstat

### ISSUE THREAD

**Issue by RongkangXiong** [coderabbit214/bibliothecarius#7]
I run `docker-compose up` in dir `./bibliothecarius` but got
```
failed to solve: lstat /var/lib/docker/tmp/buildkit-mount3053042581/build/libs: no such file or directory
```

can you help me get the solutions? Thanks!

**Comment by coderabbit214** [comment]
What environment are you using, x86 or arm?

**Comment by coderabbit214** [comment]
@RongkangXiong

**Comment by coderabbit214** [comment]
This commit is processed.https://github.com/coderabbit214/bibliothecarius/commit/2eb6d6f50a8fdf5e5467680c195ee309c5809e15
